# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target "AuthenticatorUser" do
  pod "EosioSwift", "~> 0.2.1" # pod for this library
  # Providers for EOSIO SDK for Swift
  pod "EosioSwiftAbieosSerializationProvider", "~> 0.2.1" # serialization provider
  pod "EosioSwiftSoftkeySignatureProvider", "~> 0.2.1" # experimental signature provider for development only
end
